### ISSUE TITLE
Socket hangup

### ISSUE THREAD

**Issue by meker12** [deconst/strider-deconst-content#13]
This might resolve itself, but : https://build.developer.rackspace.com/rackerlabs/docs-cloud-databases/job/56eb3976a0e4220100787121

Existing PR. Pushed additional changes. Preview link posted, but the Strider test progress is hung up.

**Comment by smashwilson** [comment]
Ah, I was wondering if this one would crop up. Long story short: I need to make the staging environment a bit beefier. At the moment it's a single container pair - for contrast, the production endpoint is currently served by _ten_ container pairs. When you only have one entry point it can get overwhelmed and start dropping or refusing connections.

The staging environment is running on the same box as the build server, too. I'm debating giving it its own server.

**Comment by smashwilson** [comment]
The fix should be deconst/deploy#105. :sparkles:

**Comment by meker12** [comment]
@smashwilson So, one thing that I noticed about this issue.  I eventually got a preview link for the updated PR, but it didn't seem to reflect the latest update I submitted.  I will keep an eye on that scenario for other builds, and open a new issue if required.

Is this understanding correct:
- When I submit a PR, then deconst builds me a staging preview.  
- If I submit an update to the same PR, then I deconst builds a second preview link that reflects the latest change

**Comment by smashwilson** [comment]
Yes, that's exactly what's supposed to happen.

What's odd is that, from the build log, it looks like the preparer completed successfully, which _should_ mean that the new metadata envelopes were published to the content service correctly. It isn't clear which HTTP transaction failed - if it had been an envelope or an asset publish, the preparer would have exited and caused a build failure, and you wouldn't see this in the build log:

```
All generated content submitted to the content store.
Preparer completed. { status: 0 }
```

It might have failed posting the comment to GitHub, but you said that the comment did appear eventually.

Did the incorrect preview link show a previous build, or did it mirror the production site instead?

**Comment by meker12** [comment]
It showed the previous build.  I'll watch out for this on some other PRs in progress.  But one I did yesterday seemed to be fine.

**Comment by smashwilson** [comment]
I only see one preview comment on rackerlabs/docs-cloud-databases#38, but two commits with green checks. The preview link that was generated successfully was created by [this earlier build](https://build.developer.rackspace.com/rackerlabs/docs-cloud-databases/job/56eb30c4a0e422010078711c) for commit 1fbb0c1, so it's tied to that state of the branch. The failing build ran for commit 65bbd7d but never got to post its preview link; extrapolating from the content IDs in the build output, it should have been [this one](https://staging.developer.rackspace.com/build-58838b167e/docs/cloud-databases/v1/developer-guide/).

Hmm.
