### ISSUE TITLE
Access to view Strider build results

### ISSUE THREAD

**Issue by meker12** [deconst/strider-deconst-content#15]
Sometimes I'm able to view the Strider build logs, other times I get an `unauthorized`.  Is that because something goes down?

As a user, I'd like to be able to go look at the build log for a PR or production build to make sure the logs are clean.  I think that contributors to the DevDoc and How To docs might also want to do that. 

When we have tests, or a way to send the log via e-mail, you might not need to access the Strider dashboard.

**Comment by smashwilson** [comment]
> Sometimes I'm able to view the Strider build logs, other times I get an unauthorized.

Can you give specific examples of links that do both? You should be able to see any build on the server, but not their `/config` paths, or `/admin/` paths.

> As a user, I'd like to be able to go look at the build log for a PR or production build to make sure the logs are clean. I think that contributors to the DevDoc and How To docs might also want to do that.

Yes, absolutely. If you can give me a link where you're not able to see the build logs, then it's likely a Strider bug. I can possibly investigate and send fixes upstream.

I will say that I deleted and recreated the entire build server this afternoon. The build data is all in MongoDB, so it should have been preserved, but maybe that messed something up?

> When we have tests, or a way to send the log via e-mail, you might not need to access the Strider dashboard.

I'd expect you'd always want to. Emailling build logs around wouldn't scale very well - better to have a stable URL for them (like Strider gives you) and email links to that.

Having content audit steps will make seeing that log even _more_ important. Having #9 would make it less necessary to click through, but you'd still want to be able to see context for failures.

**Comment by smashwilson** [comment]
I think I've figured out what's happening! You need to [log in at the front page](https://build.developer.rackspace.com/) before you click links directly to a build.

I'd call that a Strider bug, personally.

**Comment by meker12** [comment]
OK. That sounds like a likely cause.  I wonder how I get logged out.  I notice that the access problems seem to correlate with build issues.  For example, yesterday I made an update to the how-to repo, and it took forever for the tests to complete so it could merge.  Then, it took an hour to see the update in the repo.  After I had merged the PR, I went to look at the build results, and then I got the Not Authorized message.

**Comment by smashwilson** [comment]
Yeah, the how-to repo's build is _really slow_. (So is docs-developer-blog.) I'm wondering if the slow build correlates to your browser timing out your Strider session?

I made smashwilson/strider-github-oauth#9 to track the work for fixing that (although the actual work might end up upstream in Strider).

Mind closing this in favor of that one?

**Comment by kenperkins** [comment]
I don't think it's a login timeout; I logged in yesterday, and my first page load today and I'm still logged in.

**Comment by meker12** [comment]
Issue moved to: smashwilson/strider-github-oauth#9
